### ISSUE TITLE
‑-skipApple option breaks CLI

### ISSUE THREAD

**Issue by Ansimorph** [TrigenSoftware/flexis-favicons#236]
First of all thank you for this package and the work you put in it!

**node:** v10.16.0
**OS:** OSX 10.15.4

When running `npx favicons ./src/assets/images/favicon.png ‑-skipApple --dest dist/images` I get the follwing error:

```objc[38689]: Class GNotificationCenterDelegate is implemented in both /Users/bg/Documents/git/ganslandt.xyz/node_modules/@flexis/favicons/node_modules/sharp/vendor/lib/libgio-2.0.0.dylib (0x106013598) and /Users/bg/Documents/git/ganslandt.xyz/node_modules/canvas/build/Release/libgio-2.0.0.dylib (0x106fa6588). One of the two will be used. Which one is undefined.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /Users/bg/Documents/git/ganslandt.xyz/‑-skipApple (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/bg/Documents/git/ganslandt.xyz/node_modules/@flexis/favicons/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:286:20)
    at Glob.emit (events.js:198:13)
    at Glob._finish (/Users/bg/Documents/git/ganslandt.xyz/node_modules/glob/glob.js:197:8)
    at done (/Users/bg/Documents/git/ganslandt.xyz/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/bg/Documents/git/ganslandt.xyz/node_modules/glob/glob.js:688:12)
    at /Users/bg/Documents/git/ganslandt.xyz/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/bg/Documents/git/ganslandt.xyz/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/bg/Documents/git/ganslandt.xyz/node_modules/glob/glob.js:764:12)
    at RES (/Users/bg/Documents/git/ganslandt.xyz/node_modules/inflight/inflight.js:31:16)
Emitted 'error' event at:
    at Pumpify.emit (events.js:198:13)
    at Pumpify.Duplexify._destroy (/Users/bg/Documents/git/ganslandt.xyz/node_modules/duplexify/index.js:191:15)
    at /Users/bg/Documents/git/ganslandt.xyz/node_modules/duplexify/index.js:182:10
    at process._tickCallback (internal/process/next_tick.js:61:11)```

**Comment by dangreen** [comment]
@Ansimorph Hi!

> `‑-skipApple`

First char is not dash.
