### ISSUE TITLE
Error: Expected width, height, channels and background to create a new input image

### ISSUE THREAD

**Issue by DanielRuf** [TrigenSoftware/flexis-favicons#86]
I get the following when I try to use the CLI:

```shell
yarn exec -- favicons src/default/favicon.png -d output
yarn exec v1.19.0
(node:3035) UnhandledPromiseRejectionWarning: Error: Expected width, height, channels and background to create a new input image
    at Sharp._createInputDescriptor (/home/druf/Schreibtisch/projects/favicons-generator/node_modules/@flexis/favicons/node_modules/sharp/lib/input.js:96:15)
    at new Sharp (/home/druf/Schreibtisch/projects/favicons-generator/node_modules/@flexis/favicons/node_modules/sharp/lib/constructor.js:225:29)
    at Sharp (/home/druf/Schreibtisch/projects/favicons-generator/node_modules/@flexis/favicons/node_modules/sharp/lib/constructor.js:106:12)
    at createCanvas (/home/druf/Schreibtisch/projects/favicons-generator/node_modules/@flexis/favicons/lib/index.js:402:10)
    at renderIcon (/home/druf/Schreibtisch/projects/favicons-generator/node_modules/@flexis/favicons/lib/index.js:385:24)
    at FaviconsGenerator.generateIcon (/home/druf/Schreibtisch/projects/favicons-generator/node_modules/@flexis/favicons/lib/index.js:914:24)
    at /home/druf/Schreibtisch/projects/favicons-generator/node_modules/@flexis/favicons/lib/index.js:885:22
    at Generator.next (<anonymous>)
    at resume (/home/druf/Schreibtisch/projects/favicons-generator/node_modules/@babel/runtime/helpers/AsyncGenerator.js:27:28)
    at /home/druf/Schreibtisch/projects/favicons-generator/node_modules/@babel/runtime/helpers/AsyncGenerator.js:20:9
(node:3035) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3035) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.04s.

```

**Comment by dangreen** [comment]
Fixed in https://github.com/TrigenSoftware/flexis-favicons/pull/88

**Comment by DanielRuf** [comment]
Weird way to solve it (instead of really setting where the documentation says the default is set - in the argument parsing part) but ok.

Tested it and it works :+1:

**Comment by DanielRuf** [comment]
Right but I wonder why this was not detected. Maybe CLI should be also tested.

Because currently the whole abstraction is in the core and this is not quite clean when looking at the big cli file ;-)

**Comment by dangreen** [comment]
@DanielRuf feel free to open PR with cli tests 🙂
